[workspace]
resolver = "2"

members = [
    "shaderbg-desktop",
    "shaderbg-render",
    "shaderbg-web"
]

[workspace.dependencies]
egui = "0.22.0"
clap = { version = "4.2.4", features = ["derive"] }
log = "0.4"
pollster = "0.3.0"