# ShaderToy Demo Scene
[meta]
name = "Desert"
version = "1.0"
description = "Desert Sands - ShaderToy"
author = "wachel"

[settings]

[[ui]]
type = "text"
text = "There are no settings for this background"

[resources]
  [resources.shadertoy]
  type = "shader_toy"
  label = "Desert ShaderToy"
  src = "desert.glsl"

[[render_passes]]
type = "shader_toy"
label = "Render"
source = "shadertoy"